name: PotatoTeams
main: me.iran.potato.PotatoTeams
version: 1.0
author: Irantwomiles
softdepend: [Crystal]
commands:
  team:
    description: create a team
    aliases: [t, f, faction]
  spawnloc1:
    description: set safezone location 1
  spawnloc2:
    description: set safezone location 2
  setspawn:
    description: set spawn location
  spawn:
    description: teleport spawn
  buy:
    description: buy item
  sell:
    description: sell items
  price:
    description: get the cheapest price of an item
  balance:
    description: get your balance
    aliases: [bal, $, mulla, money, chaching, dolla, dollars, dollasign, bank, makeitrain]
  deposit:
    description: deposit gold into your account
    aliases: [d]
  withdraw:
    description: withdraw gold from your account
  go:
    description: warps
    aliases: [warp]
  bottle:
    description: bottle xp